apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-processor.fullname" . }}-scripts
  labels:
    {{- include "data-processor.labels" . | nindent 4 }}
      data:
          data-writer.sh: |
      {{ .Values.cronjob.script | indent 4 }}

      data-cleaner.sh: |
      {{ .Values.cleanupCronjob.script | indent 4 }}

      init-data.sh: |
      {{ .Values.initJob.script | indent 4 }}